# Generated by Django 4.2 on 2025-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=10, verbose_name='Combustivel')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
            },
        ),
    ]
