# Generated by Django 4.2 on 2025-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanque',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='tanque',
            name='capacidade_maxima',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Capacidade Máxima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanque',
            name='quantidade_disponivel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade disponivel'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=10, verbose_name='Tipo de Combustivel'),
        ),
    ]
