# Generated by Django 4.2 on 2025-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0002_remove_tanque_quantidade_tanque_capacidade_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='identificador_tanque',
            field=models.CharField(default='', max_length=7, verbose_name='Identificador'),
        ),
    ]
