# Generated by Django 4.2 on 2025-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0003_tanque_identificador_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='identificador_tanque',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Identificador'),
        ),
    ]
