# Generated by Django 4.2 on 2025-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0005_alter_tanque_identificador_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='identificador_tanque',
            field=models.CharField(default='TEMP001', max_length=7, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
