# Generated by Django 4.2 on 2025-08-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_setor_cargo'),
        ('tanques', '0006_alter_tanque_identificador_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='identificador_tanque',
            field=models.CharField(max_length=24, unique=True, verbose_name='Identificador'),
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=100, verbose_name='Nome do Combustível')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Imposto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
            },
        ),
        migrations.AlterField(
            model_name='tanque',
            name='tipo_combustivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanques.combustivel', verbose_name='Tipo de Combustivel'),
        ),
    ]
