# Generated by Django 4.2 on 2025-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0007_tanque_empresa_alter_tanque_identificador_tanque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='identificador_tanque',
            field=models.CharField(max_length=24, verbose_name='Identificador'),
        ),
    ]
