# Generated by Django 4.2 on 2025-09-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0008_alter_tanque_identificador_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='nome_combustivel',
            field=models.CharField(max_length=100, verbose_name='Nome do Combustível'),
        ),
    ]
