# Generated by Django 4.2 on 2025-09-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0009_alter_combustivel_nome_combustivel'),
    ]

    operations = [
    ]
