# Generated by Django 4.2 on 2025-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0010_auto_20250901_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustivel',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de compra'),
        ),
    ]
