# Generated by Django 5.2.5 on 2025-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0011_combustivel_valor_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
    ]
