# Generated by Django 5.2.5 on 2025-09-22 23:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_cargo_criado_alter_empresa_criado_and_more'),
        ('tanques', '0012_alter_combustivel_criado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.CreateModel(
            name='HistoricalCombustivel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_combustivel', models.CharField(max_length=100, verbose_name='Nome do Combustível')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('imposto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Imposto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de compra')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.empresa', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Combustível',
                'verbose_name_plural': 'historical Combustíveis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTanque',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('identificador_tanque', models.CharField(max_length=24, verbose_name='Identificador')),
                ('capacidade_maxima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade Máxima')),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade disponivel')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.empresa', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_combustivel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tanques.combustivel', verbose_name='Tipo de Combustivel')),
            ],
            options={
                'verbose_name': 'historical Tanque',
                'verbose_name_plural': 'historical Tanques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
