# Generated by Django 4.2 on 2025-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=10, verbose_name='Combustivel'),
        ),
    ]
