# Generated by Django 4.2 on 2025-08-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0005_alter_tanque_identificador_tanque'),
        ('abastecimento', '0002_alter_tanque_tipo_combustivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=100, verbose_name='Nome do Combustível')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Imposto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
            },
        ),
        migrations.CreateModel(
            name='RegistroAbatecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('litros_abastecer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade a abastecer')),
                ('valor_total_abastecimento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanques.tanque', verbose_name='Tanque')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.combustivel', verbose_name='Tipo de combustivel')),
            ],
            options={
                'verbose_name': 'Registro de Combustível',
                'verbose_name_plural': 'Registros de Combustível',
            },
        ),
        migrations.RemoveField(
            model_name='bomba',
            name='tanque',
        ),
        migrations.DeleteModel(
            name='Abastecimento',
        ),
        migrations.DeleteModel(
            name='Bomba',
        ),
        migrations.DeleteModel(
            name='Tanque',
        ),
    ]
