# Generated by Django 4.2 on 2025-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0004_rename_registroabatecimento_registroabastecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroabastecimento',
            name='valor_total_abastecimento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor total'),
        ),
    ]
