# Generated by Django 4.2 on 2025-08-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abastecimento', '0005_alter_registroabastecimento_valor_total_abastecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroabastecimento',
            name='litros_abastecer',
        ),
        migrations.AddField(
            model_name='registroabastecimento',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroabastecimento',
            name='litros_abastecido',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade a abastecida'),
            preserve_default=False,
        ),
    ]
