# Generated by Django 4.2 on 2025-08-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0006_remove_registroabastecimento_litros_abastecer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='nome_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'GASOLINE'), ('DIESEL', 'DIESEL')], max_length=100, verbose_name='Nome do Combustível'),
        ),
    ]
