# Generated by Django 4.2 on 2025-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0008_alter_combustivel_nome_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='nome_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=100, verbose_name='Nome do Combustível'),
        ),
    ]
