# Generated by Django 4.2 on 2025-08-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0007_tanque_empresa_alter_tanque_identificador_tanque_and_more'),
        ('abastecimento', '0009_alter_combustivel_nome_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroabastecimento',
            name='tipo_combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tanques.combustivel', verbose_name='Tipo de combustivel'),
        ),
        migrations.DeleteModel(
            name='Combustivel',
        ),
    ]
