# Generated by Django 4.2 on 2025-08-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bombas', '0005_alter_bomba_nome_bomba'),
        ('abastecimento', '0010_alter_registroabastecimento_tipo_combustivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroabastecimento',
            name='bomba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bombas.bomba', verbose_name='Bomba'),
        ),
    ]
