# Generated by Django 5.2.5 on 2025-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_criado_alter_fornecedor_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
