# Generated by Django 4.2 on 2025-08-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_usuario_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='empresa'),
        ),
    ]
