# Generated by Django 5.2.5 on 2025-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_cargo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
    ]
