# Generated by Django 5.2.5 on 2025-09-22 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_cargo_criado_alter_empresa_criado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='historicalempresa',
            name='nome_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='razao_social',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter exatamente 14 dígitos numéricos.')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve conter 10 ou 11 dígitos numéricos.')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='cnpj',
            field=models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter exatamente 14 dígitos numéricos.')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve conter 10 ou 11 dígitos numéricos.')], verbose_name='Telefone'),
        ),
    ]
