# Generated by Django 4.2 on 2025-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_cargo_options_alter_setor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nome_funcionario',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Funcionário'),
        ),
    ]
