# Generated by Django 4.2 on 2025-08-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('funcionarios', '0004_funcionario_nome_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
