# Generated by Django 4.2 on 2025-08-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_setor_cargo'),
        ('funcionarios', '0005_funcionario_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.cargo', verbose_name='Cargo'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
