# Generated by Django 4.2 on 2025-08-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_funcionario_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
    ]
