# Generated by Django 5.2.5 on 2025-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_funcionario_setor_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
    ]
