# Generated by Django 4.2 on 2025-08-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0005_alter_tanque_identificador_tanque'),
        ('abastecimento', '0003_combustivel_registroabatecimento_remove_bomba_tanque_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAbatecimento',
            new_name='RegistroAbastecimento',
        ),
    ]
