# Generated by Django 4.2 on 2025-08-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_cargo_empresa'),
        ('abastecimento', '0011_registroabastecimento_bomba'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroabastecimento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
