# Generated by Django 4.2 on 2025-08-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_alter_funcionario_empresa'),
        ('abastecimento', '0012_registroabastecimento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroabastecimento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
    ]
