# Generated by Django 4.2 on 2025-08-26 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abastecimento', '0013_alter_registroabastecimento_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroabastecimento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
    ]
