# Generated by Django 4.2 on 2025-09-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0010_auto_20250901_1633'),
        ('funcionarios', '0011_funcionario_setor_alter_funcionario_cargo'),
        ('empresas', '0004_cargo_empresa'),
        ('abastecimento', '0014_alter_registroabastecimento_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReabastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do reabastecimento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanques.tanque', verbose_name='Tanque')),
            ],
            options={
                'verbose_name': 'Reabastecimento',
                'verbose_name_plural': 'Reabastecimentos',
            },
        ),
    ]
