# Generated by Django 4.2 on 2025-09-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_empresa'),
        ('abastecimento', '0015_registroreabastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroreabastecimento',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='registroreabastecimento',
            name='valor_total_reabastecimento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor total do reabastecimento'),
        ),
        migrations.AlterField(
            model_name='registroreabastecimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume'),
        ),
    ]
