# Generated by Django 5.2.5 on 2025-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0016_registroreabastecimento_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroabastecimento',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='registroabastecimento',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='registroreabastecimento',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Crição'),
        ),
        migrations.AlterField(
            model_name='registroreabastecimento',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação'),
        ),
    ]
