# Generated by Django 5.2.5 on 2025-09-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0017_alter_registroabastecimento_criado_and_more'),
        ('funcionarios', '0012_alter_funcionario_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroabastecimento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
    ]
