# Generated by Django 4.2 on 2025-08-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tanques', '0002_remove_tanque_quantidade_tanque_capacidade_maxima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_bomba', models.CharField(max_length=144, verbose_name='Nome')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanques.tanque', verbose_name='Tanque')),
            ],
            options={
                'verbose_name': 'Bomba',
                'verbose_name_plural': 'Bombas',
            },
        ),
    ]
