# Generated by Django 4.2 on 2025-08-06 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0002_remove_tanque_quantidade_tanque_capacidade_maxima_and_more'),
        ('bombas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomba',
            name='tanque',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tanques.tanque', verbose_name='Tanque'),
        ),
    ]
