# Generated by Django 4.2 on 2025-08-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0005_alter_tanque_identificador_tanque'),
        ('bombas', '0002_alter_bomba_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomba',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanques.tanque', verbose_name='Tanque'),
        ),
    ]
