# Generated by Django 4.2 on 2025-08-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_setor_cargo'),
        ('tanques', '0007_tanque_empresa_alter_tanque_identificador_tanque_and_more'),
        ('bombas', '0003_alter_bomba_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomba',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='bomba',
            name='nome_bomba',
            field=models.CharField(max_length=144, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bomba',
            name='tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanques.tanque', verbose_name='Tanque'),
        ),
    ]
