# Generated by Django 4.2 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombas', '0004_bomba_empresa_alter_bomba_nome_bomba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomba',
            name='nome_bomba',
            field=models.CharField(max_length=144, verbose_name='Nome'),
        ),
    ]
